### ISSUE TITLE
Independent of go lang

### ISSUE THREAD

**Issue by tzanakis** [keybraker/Mediarizer-2#5]
Could you please create an executable from your code so that we can use this nice tool without having to install go lang in our system?

**Comment by keybraker** [comment]
This has been implemented ([here](https://github.com/keybraker/mediarizer-2/pull/9))

You can download the latest version from the main page of the project, under releases section on the right.

<img width="269" alt="Screenshot 2024-02-24 at 4 21 40 PM" src="https://github.com/keybraker/mediarizer-2/assets/23459466/f38e6bf2-e013-491d-b985-b5754d19d2b5">
